import pytest
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected

from alembic import command


def test_the_migrations_still_produce_the_schema_the_models_describe(
    migration_config: Config,
) -> None:
    """Fails the moment a model changes without a migration to match.

    The rest of the suite would not catch it on its own: it only exercises the
    columns the code happens to touch, so a drifted or missing one can sit
    green until production runs the real migrations and disagrees.
    """
    try:
        command.check(migration_config)
    except AutogenerateDiffsDetected as drift:
        pytest.fail(f"Modèles et migrations ont divergé : {drift}")
