"""create sync records

Revision ID: 95eedd6eda68
Revises: 52b857edada9
Create Date: 2026-08-22 14:11:06.452247

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "95eedd6eda68"
down_revision: str | None = "52b857edada9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


REVISION_SEQUENCE = sa.Sequence("seq_sync_records_revision")


def upgrade() -> None:
    # Autogenerate emitted the nextval() default but not the sequence it reads,
    # so this migration failed on any database that did not already have it —
    # which is every fresh one, production included. Caught by running the
    # revisions against an empty database rather than the development one.
    op.execute(sa.schema.CreateSequence(REVISION_SEQUENCE))
    op.create_table(
        "sync_records",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("entity_type", sa.String(length=32), nullable=False),
        sa.Column("entity_id", sa.String(length=64), nullable=False),
        sa.Column(
            "revision",
            sa.BigInteger(),
            server_default=sa.text("nextval('seq_sync_records_revision')"),
            nullable=False,
        ),
        sa.Column("ciphertext", sa.LargeBinary(), nullable=True),
        sa.Column("nonce", sa.LargeBinary(), nullable=True),
        sa.Column("client_updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_sync_records_user_id"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint(
            "user_id", "entity_type", "entity_id", name=op.f("pk_sync_records")
        ),
        sa.UniqueConstraint("revision", name=op.f("uq_sync_records_revision")),
    )
    op.create_index(
        "ix_sync_records_user_id_revision", "sync_records", ["user_id", "revision"], unique=False
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_sync_records_user_id_revision", table_name="sync_records")
    op.drop_table("sync_records")
    op.execute(sa.schema.DropSequence(REVISION_SEQUENCE))
